### ISSUE TITLE
division by zero error?

### ISSUE THREAD

**Issue by rossibarra** [trevorcousins/PSMCplus#2]
<img width="1433" alt="image" src="https://github.com/trevorcousins/PSMCplus/assets/2594529/ea7cff7f-7dbc-4f17-8d8c-9c877bc9dac1">

Running psmcplus on an mhs file that works for msmc2 and get this error. Any ideas?

**Comment by trevorcousins** [comment]
Hi Jeff, 

It looks as if your heterozygosity is very high (theta=0.05), so the default binsize of 100 is not appropriate and thus you are getting an error. Try instead a binsize of 10 or 20 (add `-b 10` or `-b 20` to your command line), and that should work. Please let me know how you get on. 

What species is this? Or is it a simulation. Just note that some species with really high theta (e.g. lepidoptera) typically have a recombination rate bigger than their mutation rate, which is problematic for *SMC analysis. 

Trevor

**Comment by rossibarra** [comment]
Great, will try. This is maize, not simulated. Synonymous pi is about 1.6%, but from whole genome alignment we do get close to 4%.  I don't think rho > theta genomewide, but rho does vary by a couple orders of magnitude along the genome!

**Comment by rossibarra** [comment]
Excellent using different `-b` solved.
